### PR TITLE
Functional 2.0

### PR DESCRIPTION
**Pull request by JohannesMoersch**

### CODE REVIEW

**Comment by RyanMarcotte** [comment]
The commit messages do a good job explaining everything.  I gave the code changes a cursory glance; looks good.

**Comment by RyanMarcotte** [comment]
Is there a particular reason why these changes should not be merged in?

**Comment by JohannesMoersch** [comment]
I sat on this for a while just to make sure we didn't encounter any issues with a couple services trialing the new version.

**Comment by RyanMarcotte** [comment]
Makes sense!

**Pull request merged**
