### PR TITLE
Add overloads of collection extension methods Apply and Do accepting index

### PR DESCRIPTION
**Pull request by RyanMarcotte**
- adds `Apply` extension methods accepting `Action<T, int>` (item and its position in the collection)
- adds `Do` extension methods accepting `Action<T, int>` (item and its position in the collection)
- adds a new `Collections` documentation page

### CODE REVIEW

**Comment by JohannesMoersch** [comment]
Can you also add these extensions to the NetStandard2 project as well please?

**Comment by RyanMarcotte** [comment]
Done @JohannesMoersch

**Comment by JohannesMoersch** [comment]
You'll also need to duplicate the IEnumerable and Task<IEnumerable> extensions for the Async versions. Basically anything in the AsyncEnumerables assembly needs to be duplicated.

**Comment by RyanMarcotte** [comment]
I did a search for `ApplyAsync` and `DoAsync` and made the appropriate changes.  Let me know if there are other areas that require attention @JohannesMoersch .

**Comment by JohannesMoersch** [comment]
Hmm. Either I'm crazy or I actually forgot some extensions initially then. I'll write a meta test that confirms everything has a match in the other project and then get back to you.

**Comment by RyanMarcotte** [comment]
Thanks for writing that test @JohannesMoersch .  I'll work on getting the missing methods added.

**Comment by RyanMarcotte** [comment]
The build pipeline doesn't seem to like the post-build script
```
/home/runner/work/Functional/Functional/Functional.AsyncEnumerables.NetStandard2/Functional.AsyncEnumerables.NetStandard2.csproj(18,5):
error MSB3073:
The command "xcopy "/home/runner/work/Functional/Functional/Functional.AsyncEnumerables.NetStandard2/bin/Release/netstandard2.0/Functional.AsyncEnumerables.dll" "/home/runner/work/Functional/Functional/Functional.Tests\bin\Release\netstandard2_dlls\" /s /y

/home/runner/work/Functional/Functional/Functional.AsyncEnumerables.NetStandard2/Functional.AsyncEnumerables.NetStandard2.csproj(18,5):
error MSB3073:
xcopy "/home/runner/work/Functional/Functional/Functional.AsyncEnumerables.NetStandard2/bin/Release/netstandard2.0/Functional.AsyncEnumerables.pdb" "/home/runner/work/Functional/Functional/Functional.Tests\bin\Release\netstandard2_dlls\" /s /y

exited with code 127
```

**Comment by JohannesMoersch** [comment]
Hmm. I wonder if I could make that conditional. Maybe I should make it for debug only. In any case, the missing select methods are on me. I'm gonna review a few things.

**Review by JohannesMoersch — APPROVED** [review]

**Pull request merged**
