### PR TITLE
ThrowOnNone and ThrowOnFailure extension methods

### PR DESCRIPTION
**Pull request by RyanMarcotte**
#22

### CODE REVIEW

**Comment by RyanMarcotte** [comment]
I thought about having a `ThrowIfFailure` overload that is constrained on `Exception`, but I did not include that here.  It would not save much typing.

``` csharp
Result.Failure<int, Exception>(new Exception(...)).ThrowIfFailure(e => e)
```

**Comment by RyanMarcotte** [comment]
I also did not add a `ThrowIfSuccess` method...  What is the use case for that?  If necessary, someone could `result.Transpose().ThrowIfFailure(...)`, though I admit it's a little awkward.

**Comment by deimors** [comment]
Looks good, I did have a thought on naming though: `SomeOrThrow()` / `SuccessOrThrow()` in order to communicate both possible outcomes?

Otherwise, I agree that additional extensions for throwing in the some / success cases, or specifically for `Exception`, aren't really necessary.

**Comment by RyanMarcotte** [comment]
Now that you mention it @deimors, I should keep with the naming convention used elsewhere across the repo and use `ThrowOnNone`, `ThrowOnFailure`.

**Review by deimors — APPROVED** [review]
Yea, looks good to me

**Pull request merged**
